import React, { useState } from 'react';
import { Calendar, Sparkles, Plus, Clock, Play, Flame, CheckCircle, ArrowRight } from 'lucide-react';
import { YouTubeChannel, VideoContent } from '../types';

interface BatchGeneratorProps {
  channel: YouTubeChannel;
  onBatchSchedule: (posts: VideoContent[]) => void;
}

export const BatchGenerator: React.FC<BatchGeneratorProps> = ({
  channel,
  onBatchSchedule,
}) => {
  const [days, setDays] = useState<number>(7);
  const [isGenerating, setIsGenerating] = useState(false);
  const [batchItems, setBatchItems] = useState<any[]>([]);
  const [isPushed, setIsPushed] = useState(false);

  const handleGenerateBatch = async () => {
    setIsGenerating(true);
    setIsPushed(false);

    try {
      const res = await fetch('/api/gemini/generate-batch', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          channelTitle: channel.title,
          niche: channel.niche,
          days,
          cadence: channel.cadence,
          preferredTime: channel.preferredPostTimeUtc,
        }),
      });

      const data = await res.json();
      if (data.success && Array.isArray(data.items)) {
        setBatchItems(data.items);
      }
    } catch (err) {
      console.error('Failed to generate batch:', err);
    } finally {
      setIsGenerating(false);
    }
  };

  const handlePushAllToQueue = () => {
    if (!batchItems.length) return;

    const newPosts: VideoContent[] = batchItems.map((item, idx) => {
      const targetDate = new Date();
      targetDate.setDate(targetDate.getDate() + (idx + 1));
      const isoDate = `${targetDate.toISOString().split('T')[0]}T${channel.preferredPostTimeUtc || '16:00'}:00Z`;

      return {
        id: `batch-${Date.now()}-${idx}`,
        channelId: channel.id,
        format: item.format === 'short' ? 'short' : 'video',
        title: item.title,
        titleOptions: [
          { title: item.title, predictedCtr: item.predictedCtr || 11.2, curiosityScore: 90 }
        ],
        hook: item.hook || `Discover the truth behind ${item.coreTopic}`,
        script: `Full video script covering ${item.coreTopic}. Structured for maximum algorithmic watch time and retention.`,
        scriptSections: [
          {
            timestamp: '00:00',
            heading: 'Viral Hook',
            narration: item.hook || 'Here is what you need to know today.',
            visualCue: 'Dynamic kinetic typography with fast cutaways'
          }
        ],
        description: `${item.title}\n\nAutomated consistent posting via AutoTube Studio.\n\nSubscribe for daily updates!\n#YouTube #Consistency #Tech`,
        tags: [channel.category.toLowerCase(), 'tutorial', 'breakdown', 'ai'],
        thumbnailHeadline: item.title.slice(0, 20).toUpperCase(),
        thumbnailConcept: 'High-contrast neon subject with focal depth',
        thumbnailPrompt: 'Clean YouTube thumbnail render, vibrant contrast, dark slate tech background',
        thumbnailUrl: '/src/assets/images/studio_thumbnail_sample_1790790972715.jpg',
        pinnedComment: 'What are your thoughts on this topic? Let us know below!',
        estimatedDuration: item.format === 'short' ? '00:50' : '11:30',
        status: 'scheduled',
        scheduledFor: isoDate,
        createdAt: new Date().toISOString(),
        isAutoGenerated: true,
      };
    });

    onBatchSchedule(newPosts);
    setIsPushed(true);
    setTimeout(() => setIsPushed(false), 3000);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-800">
        <div>
          <h2 className="text-xl font-bold tracking-tight text-white flex items-center gap-2">
            <Calendar className="w-5 h-5 text-amber-500" />
            Consistency Batch Planner
          </h2>
          <p className="text-xs text-slate-400 mt-0.5">
            Maintain an unbroken YouTube posting streak by generating a multi-day structured content calendar in 1 click.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <div className="flex items-center p-1 bg-slate-900 border border-slate-800 rounded-xl text-xs">
            <button
              onClick={() => setDays(7)}
              className={`px-3 py-1.5 rounded-lg transition-colors font-medium ${
                days === 7 ? 'bg-slate-800 text-white' : 'text-slate-400 hover:text-white'
              }`}
            >
              7-Day Sprint
            </button>
            <button
              onClick={() => setDays(14)}
              className={`px-3 py-1.5 rounded-lg transition-colors font-medium ${
                days === 14 ? 'bg-slate-800 text-white' : 'text-slate-400 hover:text-white'
              }`}
            >
              14-Day Calendar
            </button>
            <button
              onClick={() => setDays(30)}
              className={`px-3 py-1.5 rounded-lg transition-colors font-medium ${
                days === 30 ? 'bg-slate-800 text-white' : 'text-slate-400 hover:text-white'
              }`}
            >
              30-Day Omnipresence
            </button>
          </div>

          <button
            onClick={handleGenerateBatch}
            disabled={isGenerating}
            className="px-4 py-2 bg-rose-600 hover:bg-rose-500 active:bg-rose-700 disabled:opacity-50 text-white text-xs font-semibold rounded-xl shadow-md shadow-rose-600/20 transition-all flex items-center gap-1.5 whitespace-nowrap"
          >
            {isGenerating ? (
              <>
                <span className="w-3.5 h-3.5 border-2 border-white/20 border-t-white rounded-full animate-spin" />
                Generating Plan...
              </>
            ) : (
              <>
                <Sparkles className="w-4 h-4" />
                Generate {days}-Day Calendar
              </>
            )}
          </button>
        </div>
      </div>

      {/* Generated Batch Table */}
      {batchItems.length > 0 ? (
        <div className="space-y-4 animate-fade-in">
          <div className="flex items-center justify-between p-3.5 rounded-xl bg-slate-900 border border-slate-800">
            <div className="text-xs text-slate-300 flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
              <span>Ready to schedule <strong className="text-white">{batchItems.length} videos</strong> across the next {days} days at <strong className="text-white">{channel.preferredPostTimeUtc} UTC</strong></span>
            </div>

            <button
              onClick={handlePushAllToQueue}
              disabled={isPushed}
              className="px-4 py-2 bg-emerald-600 hover:bg-emerald-500 active:bg-emerald-700 disabled:opacity-70 text-white text-xs font-semibold rounded-xl shadow-md shadow-emerald-600/20 transition-all flex items-center gap-1.5"
            >
              {isPushed ? (
                <>
                  <CheckCircle className="w-4 h-4" />
                  Scheduled in Auto-Poster!
                </>
              ) : (
                <>
                  <Plus className="w-4 h-4" />
                  Push All to Upload Queue
                </>
              )}
            </button>
          </div>

          <div className="grid grid-cols-1 gap-2.5">
            {batchItems.map((item, index) => {
              const isShort = item.format === 'short';
              return (
                <div
                  key={index}
                  className="p-4 rounded-xl bg-slate-900 border border-slate-800 hover:border-slate-700 transition-colors flex flex-col md:flex-row md:items-center justify-between gap-3"
                >
                  <div className="flex items-start gap-3">
                    <div className="w-8 h-8 rounded-lg bg-slate-950 border border-slate-800 flex items-center justify-center text-xs font-mono font-bold text-slate-400 shrink-0">
                      D{item.dayNumber || index + 1}
                    </div>

                    <div className="space-y-1">
                      <div className="flex items-center gap-2">
                        <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded text-[11px] font-medium ${
                          isShort 
                            ? 'bg-amber-500/10 text-amber-400 border border-amber-500/20' 
                            : 'bg-rose-500/10 text-rose-400 border border-rose-500/20'
                        }`}>
                          {isShort ? <Flame className="w-3 h-3" /> : <Play className="w-3 h-3" />}
                          {isShort ? 'Short (9:16)' : 'Full Video'}
                        </span>
                        <span className="text-xs text-slate-500 font-mono">
                          {channel.preferredPostTimeUtc} UTC
                        </span>
                        <span className="text-xs text-emerald-400 font-mono tabular-nums">
                          {item.predictedCtr || 11.2}% Est. CTR
                        </span>
                      </div>

                      <h4 className="text-sm font-semibold text-white leading-snug">
                        {item.title}
                      </h4>

                      <p className="text-xs text-slate-400 line-clamp-1 italic">
                        Hook: "{item.hook}"
                      </p>
                    </div>
                  </div>

                  <div className="flex items-center gap-2 shrink-0 md:self-center">
                    <span className="text-[11px] text-slate-400 bg-slate-950 px-2.5 py-1 rounded-lg border border-slate-800">
                      Day +{index + 1}
                    </span>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      ) : (
        <div className="p-12 rounded-2xl bg-slate-900/50 border border-slate-800/80 text-center space-y-3">
          <div className="w-12 h-12 rounded-2xl bg-amber-500/10 border border-amber-500/20 text-amber-400 flex items-center justify-center mx-auto">
            <Calendar className="w-6 h-6" />
          </div>
          <h3 className="text-sm font-semibold text-white">No Batch Plan Generated Yet</h3>
          <p className="text-xs text-slate-400 max-w-md mx-auto">
            Select 7, 14, or 30 days and click "Generate Calendar" to let Gemini map out a viral, consistent posting strategy for {channel.title}.
          </p>
          <button
            onClick={handleGenerateBatch}
            className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-xs font-medium text-white rounded-xl transition-colors inline-flex items-center gap-1.5"
          >
            <Sparkles className="w-4 h-4 text-amber-400" />
            Generate 7-Day Strategy Now
          </button>
        </div>
      )}
    </div>
  );
};
