import React, { useState } from 'react';
import { 
  Sparkles, 
  Play, 
  Send, 
  Clock, 
  Copy, 
  Check, 
  Image as ImageIcon, 
  MessageSquare, 
  Tag, 
  ChevronRight, 
  Eye, 
  CheckCircle2, 
  ArrowRight,
  Flame,
  Radio
} from 'lucide-react';
import { YouTubeChannel, VideoContent, ContentFormat } from '../types';

interface ContentGeneratorProps {
  channel: YouTubeChannel;
  onSchedulePost: (post: VideoContent) => void;
  onPublishNow: (post: VideoContent) => void;
  prefillTopic?: string;
  prefillFormat?: ContentFormat;
}

export const ContentGenerator: React.FC<ContentGeneratorProps> = ({
  channel,
  onSchedulePost,
  onPublishNow,
  prefillTopic = '',
  prefillFormat = 'video',
}) => {
  const [topic, setTopic] = useState(prefillTopic || 'Building Autonomous AI Coding Agents with Gemini Live');
  const [format, setFormat] = useState<ContentFormat>(prefillFormat);
  const [tone, setTone] = useState(channel.tone || 'High-energy, authoritative, zero-fluff');
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedData, setGeneratedData] = useState<any>(null);
  const [selectedTitle, setSelectedTitle] = useState('');
  const [copiedKey, setCopiedKey] = useState<string | null>(null);
  const [scheduledDate, setScheduledDate] = useState(() => {
    const d = new Date();
    d.setDate(d.getDate() + 1);
    return d.toISOString().split('T')[0];
  });
  const [scheduledTime, setScheduledTime] = useState(channel.preferredPostTimeUtc || '16:00');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [activeTab, setActiveTab] = useState<'script' | 'metadata' | 'thumbnail'>('script');

  const copyToClipboard = (text: string, key: string) => {
    navigator.clipboard.writeText(text);
    setCopiedKey(key);
    setTimeout(() => setCopiedKey(null), 1800);
  };

  const handleGenerate = async () => {
    if (!topic.trim()) return;
    setIsGenerating(true);
    setGeneratedData(null);

    try {
      const res = await fetch('/api/gemini/generate-content', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          topic: topic.trim(),
          format,
          niche: channel.niche,
          targetAudience: channel.targetAudience,
          tone,
          channelTitle: channel.title,
        }),
      });

      const result = await res.json();
      if (result.success && result.data) {
        setGeneratedData(result.data);
        setSelectedTitle(result.data.mainTitle);
      }
    } catch (err) {
      console.error('Failed to generate content:', err);
    } finally {
      setIsGenerating(false);
    }
  };

  const buildPostObject = (status: 'scheduled' | 'publishing'): VideoContent => {
    const combinedIso = `${scheduledDate}T${scheduledTime}:00Z`;
    return {
      id: `post-${Date.now()}`,
      channelId: channel.id,
      format,
      title: selectedTitle || generatedData?.mainTitle || topic,
      titleOptions: generatedData?.titleOptions || [],
      hook: generatedData?.hook || '',
      script: generatedData?.fullScriptSummary || '',
      scriptSections: generatedData?.scriptSections || [],
      description: generatedData?.description || '',
      tags: generatedData?.tags || [],
      thumbnailHeadline: generatedData?.thumbnailHeadline || 'VIRAL VIDEO',
      thumbnailConcept: generatedData?.thumbnailConcept || '',
      thumbnailPrompt: generatedData?.thumbnailPrompt || '',
      thumbnailUrl: '/src/assets/images/studio_thumbnail_sample_1790790972715.jpg',
      pinnedComment: generatedData?.pinnedComment || '',
      estimatedDuration: generatedData?.estimatedDuration || (format === 'short' ? '00:50' : '12:00'),
      status,
      scheduledFor: combinedIso,
      createdAt: new Date().toISOString(),
      isAutoGenerated: true,
    };
  };

  const handleSchedule = () => {
    if (!generatedData) return;
    setIsSubmitting(true);
    const post = buildPostObject('scheduled');
    setTimeout(() => {
      onSchedulePost(post);
      setIsSubmitting(false);
    }, 400);
  };

  const handlePublishImmediately = () => {
    if (!generatedData) return;
    setIsSubmitting(true);
    const post = buildPostObject('publishing');
    onPublishNow(post);
    setIsSubmitting(false);
  };

  return (
    <div className="space-y-6">
      {/* Top Banner / Headline */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-800">
        <div>
          <h2 className="text-xl font-bold tracking-tight text-white flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-rose-500" />
            AI Video Production Studio
          </h2>
          <p className="text-xs text-slate-400 mt-0.5">
            Engineered with Gemini to generate viral titles, retention hooks, full scripts, and SEO metadata.
          </p>
        </div>

        <div className="flex items-center gap-2 text-xs text-slate-400 bg-slate-900 border border-slate-800 px-3 py-1.5 rounded-lg">
          <span className="text-slate-500">Targeting:</span>
          <span className="font-medium text-slate-200">{channel.title}</span>
          <span>·</span>
          <span className="text-rose-400">{channel.niche.slice(0, 24)}...</span>
        </div>
      </div>

      {/* Input Form Card */}
      <div className="p-5 rounded-2xl bg-slate-900 border border-slate-800 shadow-sm space-y-4">
        <div>
          <label className="block text-xs font-semibold text-slate-300 mb-1.5">
            Video Topic / Core Angle
          </label>
          <div className="flex flex-col sm:flex-row gap-2">
            <input
              type="text"
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
              placeholder="e.g. 5 AI Agents That Automate Software Development in 2026"
              className="flex-1 px-3.5 py-2.5 bg-slate-950 border border-slate-800 rounded-xl text-sm text-white placeholder-slate-500 focus:outline-none focus:border-rose-500 focus:ring-1 focus:ring-rose-500 transition-all"
            />
            <button
              onClick={handleGenerate}
              disabled={isGenerating || !topic.trim()}
              className="px-5 py-2.5 bg-rose-600 hover:bg-rose-500 active:bg-rose-700 disabled:opacity-50 text-white text-xs font-semibold rounded-xl shadow-md shadow-rose-600/20 transition-all flex items-center justify-center gap-2 whitespace-nowrap"
            >
              {isGenerating ? (
                <>
                  <span className="w-4 h-4 border-2 border-white/20 border-t-white rounded-full animate-spin" />
                  Generating Master Package...
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4" />
                  Generate Package
                </>
              )}
            </button>
          </div>
        </div>

        {/* Format & Tone controls */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 pt-1">
          <div>
            <label className="block text-xs font-medium text-slate-400 mb-1">
              Content Format
            </label>
            <div className="grid grid-cols-2 gap-1.5 p-1 bg-slate-950 rounded-xl border border-slate-800">
              <button
                type="button"
                onClick={() => setFormat('video')}
                className={`py-1.5 text-xs font-medium rounded-lg transition-colors flex items-center justify-center gap-1.5 ${
                  format === 'video' ? 'bg-slate-800 text-white shadow-sm' : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                <Play className="w-3.5 h-3.5 text-rose-400" />
                Long Video
              </button>
              <button
                type="button"
                onClick={() => setFormat('short')}
                className={`py-1.5 text-xs font-medium rounded-lg transition-colors flex items-center justify-center gap-1.5 ${
                  format === 'short' ? 'bg-slate-800 text-white shadow-sm' : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                <Flame className="w-3.5 h-3.5 text-amber-400" />
                Shorts (9:16)
              </button>
            </div>
          </div>

          <div>
            <label className="block text-xs font-medium text-slate-400 mb-1">
              Script Tone & Style
            </label>
            <select
              value={tone}
              onChange={(e) => setTone(e.target.value)}
              className="w-full px-3 py-2 bg-slate-950 border border-slate-800 rounded-xl text-xs text-white focus:outline-none focus:border-rose-500"
            >
              <option value="High-energy, authoritative, zero-fluff">High-energy & Authoritative</option>
              <option value="Documentary, analytical, deep narrative">Documentary & Deep Dive</option>
              <option value="Practical code-first walkthrough">Code-First & Practical</option>
              <option value="Sensational, provocative, fast hook">Provocative & Viral Hook</option>
            </select>
          </div>

          <div>
            <label className="block text-xs font-medium text-slate-400 mb-1">
              Suggested Topics
            </label>
            <div className="flex items-center gap-1 overflow-x-auto py-0.5">
              <button
                type="button"
                onClick={() => setTopic('Why Python is Being Rewritten in Rust')}
                className="px-2 py-1 text-[11px] rounded-lg bg-slate-950 hover:bg-slate-800 border border-slate-800 text-slate-300 whitespace-nowrap"
              >
                🦀 Rust vs Python
              </button>
              <button
                type="button"
                onClick={() => setTopic('Autonomous AI Agents Explained in 60s')}
                className="px-2 py-1 text-[11px] rounded-lg bg-slate-950 hover:bg-slate-800 border border-slate-800 text-slate-300 whitespace-nowrap"
              >
                🤖 AI Agents 60s
              </button>
              <button
                type="button"
                onClick={() => setTopic('The 2026 YouTube Algorithm Secret')}
                className="px-2 py-1 text-[11px] rounded-lg bg-slate-950 hover:bg-slate-800 border border-slate-800 text-slate-300 whitespace-nowrap"
              >
                📈 Algorithm 2026
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Generated Content Showcase */}
      {generatedData ? (
        <div className="space-y-5 animate-fade-in">
          {/* Title Variations & CTR Predictor */}
          <div className="p-5 rounded-2xl bg-slate-900 border border-slate-800 shadow-sm space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-xs font-semibold text-slate-300 uppercase tracking-wider flex items-center gap-1.5">
                <Sparkles className="w-3.5 h-3.5 text-amber-400" />
                Select Primary Title (With AI CTR & Curiosity Ratings)
              </span>
              <span className="text-xs text-slate-500 font-mono">
                Duration: {generatedData.estimatedDuration}
              </span>
            </div>

            <div className="grid grid-cols-1 gap-2">
              {generatedData.titleOptions?.map((item: any, idx: number) => {
                const isSelected = (selectedTitle || generatedData.mainTitle) === item.title;
                return (
                  <div
                    key={idx}
                    onClick={() => setSelectedTitle(item.title)}
                    className={`p-3 rounded-xl border text-left cursor-pointer transition-all flex items-center justify-between gap-3 ${
                      isSelected
                        ? 'bg-rose-500/10 border-rose-500/40 text-white shadow-sm'
                        : 'bg-slate-950 border-slate-800/80 text-slate-300 hover:border-slate-700'
                    }`}
                  >
                    <div className="flex items-center gap-3">
                      <div className={`w-5 h-5 rounded-full flex items-center justify-center text-xs shrink-0 ${
                        isSelected ? 'bg-rose-500 text-white' : 'bg-slate-800 text-slate-400'
                      }`}>
                        {isSelected ? <Check className="w-3 h-3" /> : idx + 1}
                      </div>
                      <span className="text-sm font-medium">{item.title}</span>
                    </div>

                    <div className="flex items-center gap-2 shrink-0">
                      <span className="text-xs px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 font-mono tabular-nums">
                        {item.predictedCtr}% CTR
                      </span>
                      <span className="text-xs px-2 py-0.5 rounded bg-indigo-500/10 text-indigo-400 border border-indigo-500/20 font-mono tabular-nums">
                        {item.curiosityScore}/100
                      </span>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* 5-Second Retention Hook */}
          <div className="p-4 rounded-2xl bg-amber-500/5 border border-amber-500/20 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
            <div>
              <div className="text-xs font-semibold text-amber-400 flex items-center gap-1.5 mb-1">
                <Flame className="w-3.5 h-3.5 fill-amber-400" />
                5-Second Word-for-Word Retention Hook
              </div>
              <p className="text-sm text-slate-200 italic font-medium leading-relaxed">
                "{generatedData.hook}"
              </p>
            </div>
            <button
              onClick={() => copyToClipboard(generatedData.hook, 'hook')}
              className="px-2.5 py-1.5 rounded-lg bg-amber-500/15 hover:bg-amber-500/25 text-amber-300 text-xs font-medium transition-colors shrink-0 flex items-center gap-1"
            >
              {copiedKey === 'hook' ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
              {copiedKey === 'hook' ? 'Copied' : 'Copy Hook'}
            </button>
          </div>

          {/* Section Navigator Tabs */}
          <div className="flex items-center gap-2 border-b border-slate-800 pb-2">
            <button
              onClick={() => setActiveTab('script')}
              className={`px-3 py-1.5 text-xs font-medium rounded-lg transition-colors flex items-center gap-1.5 ${
                activeTab === 'script' ? 'bg-slate-800 text-white' : 'text-slate-400 hover:text-white'
              }`}
            >
              <Play className="w-3.5 h-3.5 text-rose-400" />
              Full Production Script ({generatedData.scriptSections?.length || 0} Sections)
            </button>
            <button
              onClick={() => setActiveTab('metadata')}
              className={`px-3 py-1.5 text-xs font-medium rounded-lg transition-colors flex items-center gap-1.5 ${
                activeTab === 'metadata' ? 'bg-slate-800 text-white' : 'text-slate-400 hover:text-white'
              }`}
            >
              <Tag className="w-3.5 h-3.5 text-indigo-400" />
              Description & SEO Tags
            </button>
            <button
              onClick={() => setActiveTab('thumbnail')}
              className={`px-3 py-1.5 text-xs font-medium rounded-lg transition-colors flex items-center gap-1.5 ${
                activeTab === 'thumbnail' ? 'bg-slate-800 text-white' : 'text-slate-400 hover:text-white'
              }`}
            >
              <ImageIcon className="w-3.5 h-3.5 text-emerald-400" />
              Thumbnail & Visuals
            </button>
          </div>

          {/* Tab 1: Script Sections */}
          {activeTab === 'script' && (
            <div className="space-y-3">
              {generatedData.scriptSections?.map((sec: any, index: number) => (
                <div key={index} className="p-4 rounded-xl bg-slate-900 border border-slate-800 space-y-2">
                  <div className="flex items-center justify-between text-xs">
                    <span className="font-mono text-rose-400 font-semibold bg-rose-500/10 px-2 py-0.5 rounded">
                      {sec.timestamp}
                    </span>
                    <span className="font-semibold text-slate-200">{sec.heading}</span>
                    {sec.sfxCue && (
                      <span className="text-[11px] text-slate-500 font-mono">
                        SFX: {sec.sfxCue}
                      </span>
                    )}
                  </div>

                  <p className="text-sm text-slate-300 leading-relaxed font-sans">
                    {sec.narration}
                  </p>

                  <div className="pt-2 border-t border-slate-800/80 flex flex-col sm:flex-row sm:items-center justify-between gap-2 text-xs">
                    <div className="text-slate-400 flex items-center gap-1.5">
                      <span className="text-indigo-400 font-medium">B-Roll / Visual:</span>
                      <span>{sec.visualCue}</span>
                    </div>
                    {sec.onScreenText && (
                      <div className="text-amber-400 font-mono text-[11px] bg-amber-500/10 px-2 py-0.5 rounded shrink-0">
                        Text: "{sec.onScreenText}"
                      </div>
                    )}
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* Tab 2: SEO Description & Tags */}
          {activeTab === 'metadata' && (
            <div className="space-y-4">
              <div className="p-4 rounded-xl bg-slate-900 border border-slate-800 space-y-2">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-semibold text-slate-300">
                    YouTube SEO Description (Auto-Timestamps Included)
                  </span>
                  <button
                    onClick={() => copyToClipboard(generatedData.description, 'desc')}
                    className="px-2 py-1 text-xs text-slate-400 hover:text-white flex items-center gap-1"
                  >
                    {copiedKey === 'desc' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                    {copiedKey === 'desc' ? 'Copied' : 'Copy'}
                  </button>
                </div>
                <textarea
                  readOnly
                  rows={8}
                  value={generatedData.description}
                  className="w-full p-3 bg-slate-950 border border-slate-800 rounded-lg text-xs font-mono text-slate-300 leading-relaxed resize-none focus:outline-none"
                />
              </div>

              <div className="p-4 rounded-xl bg-slate-900 border border-slate-800 space-y-2">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-semibold text-slate-300">
                    High Search-Volume Tags ({generatedData.tags?.length || 0})
                  </span>
                  <button
                    onClick={() => copyToClipboard(generatedData.tags?.join(', '), 'tags')}
                    className="px-2 py-1 text-xs text-slate-400 hover:text-white flex items-center gap-1"
                  >
                    {copiedKey === 'tags' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                    {copiedKey === 'tags' ? 'Copied All' : 'Copy All'}
                  </button>
                </div>
                <div className="flex flex-wrap gap-1.5">
                  {generatedData.tags?.map((t: string, i: number) => (
                    <span
                      key={i}
                      className="px-2 py-1 rounded bg-slate-950 border border-slate-800 text-xs text-slate-300 font-mono"
                    >
                      #{t}
                    </span>
                  ))}
                </div>
              </div>

              <div className="p-4 rounded-xl bg-slate-900 border border-slate-800 space-y-2">
                <span className="text-xs font-semibold text-slate-300 flex items-center gap-1.5">
                  <MessageSquare className="w-3.5 h-3.5 text-rose-400" />
                  Recommended Pinned Comment
                </span>
                <p className="text-xs text-slate-300 bg-slate-950 p-3 rounded-lg border border-slate-800">
                  {generatedData.pinnedComment}
                </p>
              </div>
            </div>
          )}

          {/* Tab 3: Thumbnail & Concept */}
          {activeTab === 'thumbnail' && (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="p-4 rounded-xl bg-slate-900 border border-slate-800 space-y-3">
                <span className="text-xs font-semibold text-slate-300">
                  Thumbnail Composition Preview
                </span>
                <div className="relative aspect-video rounded-xl overflow-hidden border border-slate-800 group">
                  <img
                    src="/src/assets/images/studio_thumbnail_sample_1790790972715.jpg"
                    alt="Thumbnail Art"
                    referrerPolicy="no-referrer"
                    className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-slate-950/90 via-transparent to-transparent flex flex-col justify-end p-4">
                    <span className="text-xs font-mono text-rose-400 uppercase tracking-widest font-semibold">
                      Headline Overlay
                    </span>
                    <h4 className="text-lg font-black text-white uppercase tracking-tight drop-shadow-md">
                      {generatedData.thumbnailHeadline}
                    </h4>
                  </div>
                </div>

                <div className="text-xs text-slate-400">
                  <span className="font-semibold text-slate-300">Concept:</span> {generatedData.thumbnailConcept}
                </div>
              </div>

              <div className="p-4 rounded-xl bg-slate-900 border border-slate-800 space-y-3 flex flex-col justify-between">
                <div>
                  <span className="text-xs font-semibold text-slate-300">
                    AI Thumbnail Prompt (Ready for Midjourney / Gemini)
                  </span>
                  <p className="text-xs font-mono text-slate-400 bg-slate-950 p-3 rounded-lg border border-slate-800 mt-2 leading-relaxed">
                    {generatedData.thumbnailPrompt}
                  </p>
                </div>

                <button
                  onClick={() => copyToClipboard(generatedData.thumbnailPrompt, 'thumbPrompt')}
                  className="w-full py-2 bg-slate-800 hover:bg-slate-700 text-xs font-medium text-white rounded-xl transition-colors flex items-center justify-center gap-1.5"
                >
                  {copiedKey === 'thumbPrompt' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                  {copiedKey === 'thumbPrompt' ? 'Prompt Copied' : 'Copy Generation Prompt'}
                </button>
              </div>
            </div>
          )}

          {/* Action Footer: Schedule or Publish */}
          <div className="p-4 rounded-2xl bg-slate-900 border border-slate-800 flex flex-col sm:flex-row items-center justify-between gap-4">
            <div className="flex items-center gap-3 w-full sm:w-auto">
              <div className="flex items-center gap-1.5 text-xs text-slate-300">
                <Clock className="w-4 h-4 text-slate-400" />
                <span>Auto-Post Schedule:</span>
              </div>
              <input
                type="date"
                value={scheduledDate}
                onChange={(e) => setScheduledDate(e.target.value)}
                className="px-2.5 py-1.5 bg-slate-950 border border-slate-800 rounded-lg text-xs text-white focus:outline-none focus:border-rose-500 font-mono"
              />
              <input
                type="time"
                value={scheduledTime}
                onChange={(e) => setScheduledTime(e.target.value)}
                className="px-2.5 py-1.5 bg-slate-950 border border-slate-800 rounded-lg text-xs text-white focus:outline-none focus:border-rose-500 font-mono"
              />
            </div>

            <div className="flex items-center gap-2.5 w-full sm:w-auto justify-end">
              <button
                type="button"
                onClick={handleSchedule}
                disabled={isSubmitting}
                className="px-4 py-2 bg-slate-800 hover:bg-slate-700 active:bg-slate-800 disabled:opacity-50 text-xs font-medium text-white rounded-xl transition-colors flex items-center gap-1.5"
              >
                <Clock className="w-3.5 h-3.5 text-amber-400" />
                Add to Scheduled Queue
              </button>

              <button
                type="button"
                onClick={handlePublishImmediately}
                disabled={isSubmitting}
                className="px-4 py-2 bg-rose-600 hover:bg-rose-500 active:bg-rose-700 disabled:opacity-50 text-xs font-semibold text-white rounded-xl shadow-md shadow-rose-600/20 transition-all flex items-center gap-1.5"
              >
                <Radio className="w-3.5 h-3.5" />
                Publish to YouTube Now
              </button>
            </div>
          </div>
        </div>
      ) : null}
    </div>
  );
};
