export type ContentFormat = 'video' | 'short' | 'community';

export type ContentStatus = 'draft' | 'queued' | 'scheduled' | 'publishing' | 'published' | 'failed';

export interface YouTubeChannel {
  id: string;
  title: string;
  handle: string;
  avatarUrl: string;
  subscribersCount: number;
  videoCount: number;
  totalViews: number;
  category: string;
  niche: string;
  targetAudience: string;
  tone: string;
  cadence: 'daily' | 'twice-daily' | 'mwf' | 'weekly';
  preferredPostTimeUtc: string; // e.g. "17:00"
  isConnected: boolean;
  connectedAt?: string;
  defaultPrivacy: 'public' | 'unlisted' | 'private';
  authType: 'oauth' | 'api_key' | 'handle';
}

export interface ScriptSection {
  timestamp: string;
  heading: string;
  narration: string;
  visualCue: string;
  onScreenText?: string;
  sfxCue?: string;
}

export interface VideoContent {
  id: string;
  channelId: string;
  format: ContentFormat;
  title: string;
  titleOptions: { title: string; predictedCtr: number; curiosityScore: number }[];
  hook: string;
  script: string;
  scriptSections: ScriptSection[];
  description: string;
  tags: string[];
  thumbnailHeadline: string;
  thumbnailConcept: string;
  thumbnailPrompt: string;
  thumbnailUrl?: string;
  pinnedComment: string;
  estimatedDuration: string;
  status: ContentStatus;
  scheduledFor: string; // ISO date string
  publishedAt?: string;
  youtubeVideoId?: string;
  youtubeVideoUrl?: string;
  views?: number;
  likes?: number;
  commentsCount?: number;
  errorMessage?: string;
  createdAt: string;
  isAutoGenerated?: boolean;
}

export interface AutoPostSchedule {
  frequency: 'daily' | 'twice-daily' | 'mwf' | 'weekly';
  postTimeUtc: string;
  timezone: string;
  autoApproval: boolean;
  infiniteBuffer: boolean; // Auto-generate next when buffer < 3
  bufferTarget: number;
  videoVisibility: 'public' | 'unlisted' | 'private';
}

export interface AdminSettings {
  isAutoPosterActive: boolean;
  adminPassword: string; // verified on backend with 'happy087'
  apiKeyConfigured: boolean;
  youtubeApiKey?: string;
  youtubeClientId?: string;
  youtubeClientSecret?: string;
  youtubeRefreshToken?: string;
  quotaUsedToday: number;
  quotaLimitDaily: number;
  autoApproveGenerations: boolean;
  safetyFilterEnabled: boolean;
  emergencyStop: boolean;
  infiniteConsistencyMode: boolean;
}

export interface SystemLog {
  id: string;
  timestamp: string;
  type: 'info' | 'success' | 'warning' | 'error' | 'admin';
  message: string;
  details?: string;
}

export interface TrendIdea {
  id: string;
  topic: string;
  niche: string;
  searchVolume: 'Exploding' | 'High' | 'Steady';
  difficulty: 'Low' | 'Medium' | 'High';
  hookAngle: string;
  estimatedViews: string;
  suggestedFormat: ContentFormat;
}
